[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.venv
  | _build
  | build
)/
'''
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"